[project]
name = "kinohub"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.0",
    "django==6.0.1",
    "psycopg2-binary>=2.9.11",
    "python-decouple>=3.8",
]

